Pack.register({
	spec = "https://github.com/xiyaowong/transparent.nvim",
	module = "transparent",
}):load({
	event = { "ColorScheme" },
	pattern = { "*" },
	config = function(plugin)
		plugin.setup({
			groups = {
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
				"Operator",
				"Structure",
				"LineNr",
				"NonText",
				"SignColumn",
				"CursorLine",
				"CursorLineNr",
				"StatusLine",
				"StatusLineNC",
				"EndOfBuffer",
			},
			extra_groups = {
				"NormalFloat",
				"FloatBorder",
				"FloatTitle",
				"FloatFooter",
				"WinSeparator",
				"NvimTreeNormal",
			},
			exclude_groups = {},
		})
	end,
})
