return {
	g = {
		mapleader = " ",
		loaded_netrw = 1,
		loaded_netrwPlugin = 1,
		termguicolors = true,
		markdown_fenced_languages = { "ts=typescript", "js=javascript" },
	},
	opt = {
		mouse = "",
		relativenumber = true,
		number = true,
		numberwidth = 4,
		tabstop = 2,
		shiftwidth = 2,
		expandtab = true,
		autoindent = true,
		smartindent = true,
		clipboard = "unnamedplus",
		cursorline = true,
		signcolumn = "auto",
		pumheight = 10,
		pumwidth = 10,
		autoread = true,
		showmode = false,
		showtabline = 0,
		ruler = false,
		winblend = 0,
		fillchars = "eob: ",
		wildignore = "node_modules/,*.yaml,*.log,*.lock,package.json",
		winborder = "rounded",
		confirm = false,
		splitright = true,
		laststatus = 0,
	},
	diagnostic = {
		virtual_text = true,
		severity_sort = true,
		signs = {
			text = {
				[vim.diagnostic.severity.ERROR] = "󰗖 ",
				[vim.diagnostic.severity.WARN] = "󰗖 ",
				[vim.diagnostic.severity.INFO] = "󰗖 ",
				[vim.diagnostic.severity.HINT] = "󰗖 ",
			},
		},
	},
}
